Update TypeScript, lockfileVersion, and fix new TS syntax error
Needed to fix:
src/sb3.ts:1159:5 - error TS2452: An enum member cannot have a numeric name.